# Dependencies
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Sangho Ha
tagline:          
description:      'Master Student'
url:              https://sangho0804.github.io/
baseurl:          

author:
  name:           'Sangho Ha'
  url:            https://sangho0804.github.io

paginate:         7
paginate_path:    "/blog/:num/"

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/sangho0804/sangho0804.github.io
